USE QLPKNKHOA
GO

-- TAO DANH MUC
CREATE OR ALTER PROCEDURE P_CREATE_DANHMUC
	@TenDanhMuc nvarchar(30),
	@ID_DanhMuc varchar(10) = NULL
AS
	BEGIN TRAN
		IF EXISTS (SELECT * FROM DanhMucDieuTri WHERE TenDanhMuc = @TenDanhMuc)
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'TEN DANH MUC DA CO SAN', 16
			RETURN
		END

		SET @ID_DanhMuc = (SELECT MAX(ID_DanhMuc) FROM DanhMucDieuTri)
		SET @ID_DanhMuc = DBO.F_AUTO_GENERATED_ID('DM', @ID_DanhMuc)

		BEGIN TRY
			INSERT DanhMucDieuTri(ID_DanhMuc, TenDanhMuc)
				VALUES (@ID_DanhMuc, @TenDanhMuc)
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN;
			THROW 51000, 'LOI HE THONG', 16
		END CATCH

	COMMIT
	PRINT 'THEM DANH MUC DIEU TRI THANH CONG'
GO