USE QLPKNKHOA
GO

-- TAO LICH NHA SI
CREATE OR ALTER PROCEDURE P_CREATE_LICHBACSI
	@ID_NhaSi varchar(10),
	@ThoiGianTrong datetime

AS
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM TaiKhoan WHERE ID_TaiKhoan = @ID_NhaSi AND ID_TaiKhoan LIKE 'NS%')
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'KHONG TON TAI NHA SI', 16
			RETURN
		END

		IF @ThoiGianTrong <  GETDATE()
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'THOI GIAN TRONG PHAI TRONG TUONG LAI', 16
			RETURN
		END

		IF @ID_NhaSi IS NULL OR @ThoiGianTrong IS NULL
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'VUI LONG DIEN DAY DU THONG TIN NHA SI VA THOI GIAN TRONG', 16
			RETURN
		END

		BEGIN TRY
			INSERT LichBacSi(ID_NhaSi, ThoiGianTrong)
				VALUES (@ID_NhaSi, @ThoiGianTrong)
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN;
			THROW 51000, 'LOI HE THONG', 16
		END CATCH

	COMMIT
	PRINT 'THEM LICH TRONG NHA SI THANH CONG'
GO

-- CAP NHAT LICH NHA SI
CREATE OR ALTER PROCEDURE P_UPDATE_LICHBACSI
	@ID_NhaSi varchar(10),
	@CurThoiGianTrong datetime,
	@NewThoiGianTrong datetime

AS
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM TaiKhoan WHERE ID_TaiKhoan = @ID_NhaSi AND ID_TaiKhoan LIKE 'NS%')
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'KHONG TON TAI NHA SI', 16
			RETURN
		END

		IF NOT EXISTS (SELECT * FROM LichBacSi WHERE ID_NhaSi = @ID_NhaSi AND ThoiGianTrong = @CurThoiGianTrong)
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'KHONG TIM THAY LICH NHA SI TRUNG KHOP', 16
			RETURN
		END

		IF @NewThoiGianTrong <  GETDATE()
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'THOI GIAN TRONG PHAI TRONG TUONG LAI', 16
			RETURN
		END

		IF @ID_NhaSi IS NULL OR @CurThoiGianTrong IS NULL OR @NewThoiGianTrong IS NULL
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'VUI LONG DIEN DAY DU THONG TIN NHA SI VA THOI GIAN TRONG MOI', 16
			RETURN
		END

		BEGIN TRY
			UPDATE LichBacSi
			SET ThoiGianTrong = @NewThoiGianTrong
			WHERE ID_NhaSi = @ID_NhaSi AND ThoiGianTrong = @CurThoiGianTrong
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN;
			THROW 51000, 'LOI HE THONG', 16
		END CATCH

	COMMIT
	PRINT 'CAP NHAT LICH TRONG NHA SI THANH CONG'
GO

-- XOA LICH NHA SI
CREATE OR ALTER PROCEDURE P_DELETE_LICHBACSI
	@ID_NhaSi varchar(10),
	@ThoiGianTrong datetime

AS
	BEGIN TRAN
		IF NOT EXISTS (SELECT * FROM LichBacSi WHERE ID_NhaSi = @ID_NhaSi AND ThoiGianTrong = @ThoiGianTrong)
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'KHONG TIM THAY LICH', 16
			RETURN
		END

		IF @ID_NhaSi IS NULL OR @ThoiGianTrong IS NULL
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'VUI LONG DIEN DAY DU THONG TIN NHA SI VA THOI GIAN TRONG', 16
			RETURN
		END

		BEGIN TRY
			DELETE FROM LichBacSi 
				WHERE ID_NhaSi = @ID_NhaSi AND ThoiGianTrong = @ThoiGianTrong
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN;
			THROW 51000, 'LOI HE THONG', 16
		END CATCH

	COMMIT
	PRINT 'XOA LICH NHA SI THANH CONG'
GO