USE QLPKNKHOA
GO

-- TAO RANG
-- TAO RANG
CREATE OR ALTER PROCEDURE P_CREATE_MATRANG
	@TenMatRang nvarchar(30),
	@ID_MatRang varchar(10) = NULL

AS
	BEGIN TRAN
		IF EXISTS(SELECT * FROM MatRang WHERE TenMatRang = @TenMatRang)
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'MAT RANG DA CO TREN HE THONG', 16;
			RETURN
		END

		IF @TenMatRang IS NULL
		BEGIN
			ROLLBACK TRAN
			;THROW 50000, 'DIEU THIEU THONG TIN', 16
			RETURN
		END

		SELECT @ID_MatRang = (SELECT MAX(ID_MatRang) FROM MatRang)
		SET @ID_MatRang = DBO.F_AUTO_GENERATED_ID('MR', @ID_MatRang)

		BEGIN TRY
			INSERT MatRang(ID_MatRang, TenMatRang)
				VALUES (@ID_MatRang, @TenMatRang)
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN
			;THROW 51000, 'LOI HE THONG', 16
			RETURN
		END CATCH

	COMMIT TRAN
	PRINT 'THEM MAT RANG THANH CONG'
GO