USE QLPKNKHOA
GO

-- TAO RANG
CREATE OR ALTER PROCEDURE P_CREATE_RANG
	@TenRang nvarchar(30),
	@PhiDichVu int,
	@ID_Rang varchar(10) = NULL
AS
	BEGIN TRAN
		IF EXISTS(SELECT * FROM Rang WHERE TenRang = @TenRang)
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'RANG DA CO TREN HE THONG', 16
			RETURN
		END

		IF @TenRang IS NULL OR @PhiDichVu IS NULL
		BEGIN
			ROLLBACK TRAN;
			;THROW 50000, 'DIEU THIEU THONG TIN', 16
			RETURN
		END

		SET @ID_Rang = (SELECT MAX(ID_Rang) FROM Rang)
		SET @ID_Rang = DBO.F_AUTO_GENERATED_ID('RA', @ID_Rang)

		BEGIN TRY
			INSERT Rang(ID_Rang, TenRang, PhiDichVu)
				VALUES (@ID_Rang, @TenRang, @PhiDichVu)
		END TRY
		BEGIN CATCH
			ROLLBACK TRAN;
			THROW 51000, 'LOI HE THONG', 16
		END CATCH

	COMMIT
	PRINT 'THEM RANG THANH CONG'
GO