USE QLPKNKHOA
GO

CREATE OR ALTER FUNCTION F_AUTO_GENERATED_ID (@TYPE CHAR(2), @ID VARCHAR(10))
RETURNS VARCHAR(10)
AS
BEGIN
	-- NEU CHUA ID
	IF (@ID IS NULL) SET @ID = @TYPE + '00000001'
	ELSE 
	BEGIN
        SET @ID = CAST(RIGHT(@ID, 8) AS INT) + 1
        SET @ID = @TYPE + RIGHT('0000000'+ 
					CAST(@ID AS VARCHAR(8))
					, 8)
    END
    RETURN @ID
END
GO